name: My Envio Indexer
description: My Awesome Contract # Description of the project

contracts:
  - name: Pool
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed spender, uint256 value)
        requiredEntities:
          - name: EventsSummary
      - event: Burn(address indexed sender, address indexed to, uint256 amount0, uint256 amount1)
        requiredEntities:
          - name: EventsSummary
      - event: Claim(address indexed sender, address indexed recipient, uint256 amount0, uint256 amount1)
        requiredEntities:
          - name: EventsSummary
      - event: EIP712DomainChanged()
        requiredEntities:
          - name: EventsSummary
      - event: Fees(address indexed sender, uint256 amount0, uint256 amount1)
        requiredEntities:
          - name: EventsSummary
      - event: Mint(address indexed sender, uint256 amount0, uint256 amount1)
        requiredEntities:
          - name: EventsSummary
      - event: Swap(address indexed sender, address indexed to, uint256 amount0In, uint256 amount1In, uint256 amount0Out, uint256 amount1Out)
        requiredEntities:
          - name: EventsSummary
      - event: Sync(uint256 reserve0, uint256 reserve1)
        requiredEntities:
          - name: EventsSummary
      - event: Transfer(address indexed from, address indexed to, uint256 value)
        requiredEntities:
          - name: EventsSummary
networks:
  - id: 10
    start_block: 0
    contracts:
      - name: Pool
        address:
          - "0x6da98bde0068d10ddd11b468b197ea97d96f96bc"
          - "0x6d5ba400640226e24b50214d2bbb3d4db8e6e15a"
          - "0x917aa69d539d6518440dd0bea2eaac142a8d5610"
          - "0x56770b94279539416855fe29ef14b26438b5e421"
  - id: 8453
    start_block: 0
    contracts:
      - name: Pool
        address:
          - "0xb4885bc63399bf5518b994c1d0c153334ee579d0"
